// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenQuest.Api.Data;

#nullable disable

namespace OpenQuest.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenQuest.Api.Data.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geography (point)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_asset");

                    b.HasIndex("Attributes")
                        .HasDatabaseName("ix_asset_attributes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Attributes"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Attributes"), new[] { "jsonb_path_ops" });

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_asset_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("AssetTypeId", "Status")
                        .HasDatabaseName("ix_asset_asset_type_id_status");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_data_source_id_external_id");

                    b.ToTable("asset", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AssetSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("change_type");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geography (point)")
                        .HasColumnName("geom");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<Guid>("SyncRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_run_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_snapshot");

                    b.HasIndex("SyncRunId")
                        .HasDatabaseName("ix_asset_snapshot_sync_run_id");

                    b.HasIndex("AssetId", "SyncRunId")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_snapshot_asset_id_sync_run_id");

                    b.ToTable("asset_snapshot", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AssetTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attribute_schema");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_asset_type");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_type_key");

                    b.ToTable("asset_type", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AssetTypeTaskType", b =>
                {
                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<Guid>("TaskTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_type_id");

                    b.HasKey("AssetTypeId", "TaskTypeId")
                        .HasName("pk_asset_type_task_type");

                    b.HasIndex("TaskTypeId")
                        .HasDatabaseName("ix_asset_type_task_type_task_type_id");

                    b.ToTable("asset_type_task_type", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AttributeChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attribute_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExportRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("export_run_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id")
                        .HasName("pk_attribute_change");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_attribute_change_asset_id");

                    b.HasIndex("ExportRunId")
                        .HasDatabaseName("ix_attribute_change_export_run_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_attribute_change_status");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_attribute_change_submission_id");

                    b.ToTable("attribute_change", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("CenterLat")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lat");

                    b.Property<double?>("CenterLon")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lon");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultZoom")
                        .HasColumnType("integer")
                        .HasColumnName("default_zoom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_city_key");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_claim");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_claim_expires_at")
                        .HasFilter("status = 'active'");

                    b.HasIndex("QuestId", "Status")
                        .HasDatabaseName("ix_claim_quest_id_status");

                    b.HasIndex("QuestId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_claim_quest_id_user_id")
                        .HasFilter("status IN ('active','submitted')");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_claim_user_id_status");

                    b.ToTable("claim", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdapterKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adapter_key");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attribution");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_data_source");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_data_source_key");

                    b.ToTable("data_source", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CentroidLat")
                        .HasColumnType("double precision")
                        .HasColumnName("centroid_lat");

                    b.Property<double>("CentroidLon")
                        .HasColumnType("double precision")
                        .HasColumnName("centroid_lon");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Polygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geography (polygon)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_district");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_district_created_by");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_district_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("CityId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_district_city_id_key");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_district_city_id_name");

                    b.ToTable("district", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.DistrictPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_district_point");

                    b.HasIndex("DistrictId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_district_point_district_id_position");

                    b.ToTable("district_point", null, t =>
                        {
                            t.HasCheckConstraint("ck_district_point_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("OpenQuest.Api.Data.ExportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("integer")
                        .HasColumnName("change_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_export_run");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_export_run_created_by");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_export_run_data_source_id");

                    b.ToTable("export_run", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("Phash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phash");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_media_sha256");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_media_submission_id");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("AvailableAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_message_available_at_occurred_at")
                        .HasFilter("status = 'pending'");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_point_transaction");

                    b.HasIndex("DistrictId", "CreatedAt")
                        .HasDatabaseName("ix_point_transaction_district_id_created_at");

                    b.HasIndex("SubmissionId", "Reason")
                        .IsUnique()
                        .HasDatabaseName("ix_point_transaction_submission_id_reason")
                        .HasFilter("submission_id IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_point_transaction_user_id_created_at");

                    b.ToTable("point_transaction", null, t =>
                        {
                            t.HasCheckConstraint("ck_point_transaction_amount", "amount <> 0");
                        });
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int>("ClaimTtlMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("claim_ttl_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int>("GeofenceRadiusM")
                        .HasColumnType("integer")
                        .HasColumnName("geofence_radius_m");

                    b.Property<int>("MaxCompletions")
                        .HasColumnType("integer")
                        .HasColumnName("max_completions");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer")
                        .HasColumnName("reward_points");

                    b.Property<int>("SlotsTaken")
                        .HasColumnType("integer")
                        .HasColumnName("slots_taken");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("TaskConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("task_config");

                    b.Property<Guid>("TaskTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_type_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_quest");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_quest_asset_id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_quest_campaign_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_quest_created_by");

                    b.HasIndex("TaskTypeId")
                        .HasDatabaseName("ix_quest_task_type_id");

                    b.HasIndex("Status", "AssetId")
                        .HasDatabaseName("ix_quest_status_asset_id");

                    b.ToTable("quest", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_slots", "slots_taken >= 0 AND max_completions >= 1");
                        });
                });

            modelBuilder.Entity("OpenQuest.Api.Data.QuestCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetFilter")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("asset_filter");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_quest_campaign");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_quest_campaign_created_by");

                    b.ToTable("quest_campaign", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<double>("DistanceM")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_m");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)")
                        .HasColumnName("location");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_submission");

                    b.HasIndex("ClaimId")
                        .IsUnique()
                        .HasDatabaseName("ix_submission_claim_id");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_submission_reviewed_by");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_submission_status_submitted_at");

                    b.ToTable("submission", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssetsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("assets_created");

                    b.Property<int>("AssetsRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("assets_removed");

                    b.Property<int>("AssetsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("assets_updated");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<string>("SchemaHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schema_hash");

                    b.Property<string>("SnapshotKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("snapshot_key");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sync_run");

                    b.HasIndex("DataSourceId", "StartedAt")
                        .HasDatabaseName("ix_sync_run_data_source_id_started_at");

                    b.ToTable("sync_run", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.TaskTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_schema");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ResultSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_schema");

                    b.HasKey("Id")
                        .HasName("pk_task_type");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_task_type_key");

                    b.ToTable("task_type", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("role");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.UserRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_recovery_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_recovery_code_user_id");

                    b.ToTable("user_recovery_code", (string)null);
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AssetEntity", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.AssetTypeEntity", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_asset_type_asset_type_id");

                    b.HasOne("OpenQuest.Api.Data.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_data_source_data_source_id");

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AssetSnapshot", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.AssetEntity", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_snapshot_assets_asset_id");

                    b.HasOne("OpenQuest.Api.Data.SyncRun", null)
                        .WithMany()
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_snapshot_sync_run_sync_run_id");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AssetTypeTaskType", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.AssetTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_type_task_type_asset_type_asset_type_id");

                    b.HasOne("OpenQuest.Api.Data.TaskTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_type_task_type_task_type_task_type_id");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.AttributeChange", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.AssetEntity", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_change_asset_asset_id");

                    b.HasOne("OpenQuest.Api.Data.ExportRun", null)
                        .WithMany()
                        .HasForeignKey("ExportRunId")
                        .HasConstraintName("fk_attribute_change_export_runs_export_run_id");

                    b.HasOne("OpenQuest.Api.Data.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_change_submission_submission_id");

                    b.Navigation("Asset");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Claim", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claim_quest_quest_id");

                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claim_user_user_id");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.District", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_district_city_city_id");

                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_district_user_created_by");

                    b.Navigation("City");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.DistrictPoint", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_district_point_district_district_id");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.ExportRun", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_export_run_user_created_by");

                    b.HasOne("OpenQuest.Api.Data.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_export_run_data_source_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Media", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_submissions_submission_id");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.PointTransaction", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_point_transaction_district_district_id");

                    b.HasOne("OpenQuest.Api.Data.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .HasConstraintName("fk_point_transaction_submission_submission_id");

                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_point_transaction_user_user_id");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Quest", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.AssetEntity", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_asset_asset_id");

                    b.HasOne("OpenQuest.Api.Data.QuestCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("fk_quest_quest_campaign_campaign_id");

                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_user_created_by");

                    b.HasOne("OpenQuest.Api.Data.TaskTypeEntity", "TaskType")
                        .WithMany()
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_task_type_task_type_id");

                    b.Navigation("Asset");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.QuestCampaign", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_campaign_user_created_by");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.Submission", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_claim_claim_id");

                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("fk_submission_user_reviewed_by");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.SyncRun", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_run_data_source_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("OpenQuest.Api.Data.UserRecoveryCode", b =>
                {
                    b.HasOne("OpenQuest.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_recovery_code_user_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
